import { createContext, useContext, useCallback, useMemo, useState, useEffect } from 'react';
import { translateText, translateBatch } from '../lib/bhashini';

// ---------------------------------------------------------------------------
// Base Master Strings (English single source of truth)
// No hardcoded regional language data — Bhashini translates the entire app dynamically.
// ---------------------------------------------------------------------------
const BASE_STRINGS = {
  // Navigation
  dashboard: 'Home',
  fields: 'My fields',
  detect: 'Check a plant',
  cases: 'Case history',
  alerts: 'Alerts',
  profile: 'Profile',

  // Dashboard
  welcome: 'Welcome back',
  riskToday: "Today's risk",
  quickDetect: 'Spot a problem',
  quickDetectSub: 'Take or upload a photo of the affected leaf, stem or fruit',
  noAlerts: 'No active alerts right now',
  viewAll: 'View all',
  addField: 'Add a field',

  // Fields
  myFields: 'My fields',
  fieldName: 'Field name',
  crop: 'Crop',
  variety: 'Variety',
  sowingDate: 'Sowing date',
  cropStage: 'Crop stage',
  area: 'Area (acres)',
  soilType: 'Soil type',
  saveField: 'Save field',
  saving: 'Saving…',
  useMyLocation: 'Use my location',
  detectingLocation: 'Detecting…',
  locationCaptured: 'Location captured',
  locationError: 'Could not get location',
  mapPreview: 'Map preview',

  // Detect
  checkPlant: 'Check a plant',
  whichField: 'Which field is this?',
  takePhoto: 'Take or choose a photo',
  takePhotoSub: 'Clear, well-lit, close-up of the affected part works best',
  selectPhoto: 'Select photo',
  chooseAnother: 'Choose another',
  analyzePhoto: 'Analyze photo',
  analyzing: 'Analyzing…',
  locationPinned: '📍 Location pinned',

  // Chatbot & Voice
  chatTitle: 'Ask about this diagnosis',
  chatPlaceholder: 'Type or speak your question…',
  chatSend: 'Send',
  chatVoiceHint: 'Tap mic to speak',
  chatThinking: 'Thinking…',

  // General & Empty States
  noFieldsYet: 'No fields yet',
  noFieldsBody: 'Add your first field so KrishiVed can track crop stage, weather and risk for it.',
  loading: 'Loading KrishiVed…',
};

const SUPPORTED = (import.meta.env.VITE_SUPPORTED_LANGUAGES || 'en,hi,mr,pa,te,ta,kn,gu,bn')
  .split(',')
  .map((s) => s.trim());

const LABELS = {
  en: 'English',
  hi: 'हिंदी (Hindi)',
  mr: 'मराठी (Marathi)',
  pa: 'ਪੰਜਾਬੀ (Punjabi)',
  te: 'తెలుగు (Telugu)',
  ta: 'தமிழ் (Tamil)',
  kn: 'ಕನ್ನಡ (Kannada)',
  gu: 'ગુજરાતી (Gujarati)',
  bn: 'বাংলা (Bengali)',
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const initialLang = () => {
    try {
      const saved = localStorage.getItem('kv_lang');
      if (saved && SUPPORTED.includes(saved)) return saved;
    } catch {}
    return SUPPORTED[0] || 'en';
  };

  const [lang, setLangState] = useState(initialLang);
  const [translations, setTranslations] = useState(() => {
    const cached = {};
    SUPPORTED.forEach((code) => {
      if (code === 'en') {
        cached.en = BASE_STRINGS;
      } else {
        try {
          const raw = localStorage.getItem(`kv_dict_${code}`);
          if (raw) cached[code] = JSON.parse(raw);
        } catch {}
      }
    });
    return cached;
  });
  const [isTranslating, setIsTranslating] = useState(false);

  // Dynamic full-app translation triggered automatically when language changes
  useEffect(() => {
    if (lang === 'en') return;

    // Check if translation dictionary already exists in memory/cache
    const existing = translations[lang];
    const keys = Object.keys(BASE_STRINGS);
    const hasAllKeys = existing && keys.every((k) => Boolean(existing[k]));

    if (hasAllKeys) return;

    let isMounted = true;
    setIsTranslating(true);

    const valuesToTranslate = keys.map((k) => BASE_STRINGS[k]);

    translateBatch(valuesToTranslate, 'en', lang)
      .then((translatedValues) => {
        if (!isMounted) return;

        const newDict = {};
        keys.forEach((key, idx) => {
          newDict[key] = translatedValues[idx] || BASE_STRINGS[key];
        });

        setTranslations((prev) => ({ ...prev, [lang]: newDict }));

        try {
          localStorage.setItem(`kv_dict_${lang}`, JSON.stringify(newDict));
        } catch {}
      })
      .catch((err) => {
        console.warn(`Dynamic translation to ${lang} encountered an issue:`, err);
      })
      .finally(() => {
        if (isMounted) setIsTranslating(false);
      });

    return () => {
      isMounted = false;
    };
  }, [lang, translations]);

  // t(key) — returns translated string generated by Bhashini for the active language
  const t = useCallback(
    (key) => {
      if (lang === 'en') return BASE_STRINGS[key] ?? key;
      return translations[lang]?.[key] ?? BASE_STRINGS[key] ?? key;
    },
    [lang, translations]
  );

  /**
   * translateDynamic(text) — translate arbitrary runtime text (predictions, diagnoses, chatbot messages)
   * on the fly via Bhashini NMT API into the current active language.
   */
  const translateDynamic = useCallback(
    async (text, sourceLang = 'en') => {
      if (lang === sourceLang || !text || !text.trim()) return text;
      try {
        return await translateText(text, sourceLang, lang);
      } catch {
        return text;
      }
    },
    [lang]
  );

  function setLang(code) {
    setLangState(code);
    try {
      localStorage.setItem('kv_lang', code);
    } catch {}
  }

  return (
    <LanguageContext.Provider
      value={{
        lang,
        setLang,
        t,
        translateDynamic,
        isTranslating,
        supportedLanguages: SUPPORTED,
        labels: LABELS,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
