# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNwRPtis7mZVYwFA47e1hXHeJFZlc0Nr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import zipfile
import os
import json

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
from torchvision import transforms, datasets
from torch.utils.data import DataLoader, random_split
from tqdm import tqdm
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from google.colab import drive


# Mount Google Drive
drive.mount('/content/drive')

# Check GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Define paths
DRIVE_PATH = '/content/drive/MyDrive/CNN Model'
MODEL_PATH = '/content/drive/MyDrive/best_cnn_model.pth'
DATASET_PATH = '/content/dataset'
ZIP_PATH = f"{DRIVE_PATH}/archive (6).zip"

from google.colab import drive
drive.mount('/content/drive')

# Only extract if dataset doesn't exist
if not os.path.exists(f'{DATASET_PATH}/cotton'):
    print("Extracting dataset...")
    with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
        zip_ref.extractall(DATASET_PATH)
    print("✓ Dataset extracted successfully!")
else:
    print("✓ Dataset already exists, skipping extraction")

"""Define Transforms

"""

train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomRotation(10),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

print("✓ Transforms defined")

# ============================================================================
# CELL 4: LOAD & SPLIT DATASET
# ============================================================================

print("Loading dataset...")
full_dataset = datasets.ImageFolder(f'{DATASET_PATH}/cotton', transform=train_transform)

# Split into train (80%) and test (20%)
train_size = int(0.8 * len(full_dataset))
test_size = len(full_dataset) - train_size

train_dataset, test_dataset = random_split(full_dataset, [train_size, test_size])

# Update test dataset transform (no augmentation for test)
test_dataset.dataset.transform = test_transform

# Create DataLoaders
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False, num_workers=2)

print(f"✓ Total samples: {len(full_dataset)}")
print(f"  - Training samples: {train_size} (80%)")
print(f"  - Test samples: {test_size} (20%)")
print(f"  - Classes: {full_dataset.classes}")

""" Define CNN Model"""

class CNN(nn.Module):
    def __init__(self, num_classes):
        super(CNN, self).__init__()

        self.features = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),

            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),

            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),

            nn.Conv2d(128, 256, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),
        )

        self.classifier = nn.Sequential(
            nn.Linear(256 * 14 * 14, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(0.5),
            nn.Linear(512, 256),
            nn.ReLU(inplace=True),
            nn.Dropout(0.5),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), -1)
        x = self.classifier(x)
        return x

model = CNN(num_classes=4).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.1)

print("✓ Model initialized")

"""Initializeing the model"""

if os.path.exists(MODEL_PATH):
    # Load pre-trained model
    print("Loading pre-trained model from Google Drive...")
    model.load_state_dict(torch.load(MODEL_PATH))
    model.eval()
    print("✓ Model loaded successfully! Ready for evaluation.")
    RETRAIN = False
else:
    print("No pre-trained model found. You can train now.")
    RETRAIN = True

"""Training the CNN"""

# ============================================================================
# CELL 8: TRAIN MODEL (Skip if model is already trained)
# ============================================================================

if RETRAIN:
    print("\n" + "="*60)
    print("STARTING TRAINING")
    print("="*60 + "\n")

    num_epochs = 25
    best_accuracy = 0.0
    train_losses = []
    train_accuracies = []

    for epoch in range(num_epochs):
        model.train()
        total_loss = 0
        correct = 0
        total = 0

        pbar = tqdm(train_loader, desc=f"Epoch [{epoch+1}/{num_epochs}]")

        for images, labels in pbar:
            images, labels = images.to(device), labels.to(device)

            # Forward pass
            outputs = model(images)
            loss = criterion(outputs, labels)

            # Backward and optimize
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            # Statistics
            total_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

            # Update progress bar
            pbar.set_postfix({
                'Loss': f'{total_loss / (total / 32):.4f}',
                'Acc': f'{100 * correct / total:.2f}%'
            })

        # Average loss and accuracy for epoch
        avg_loss = total_loss / len(train_loader)
        accuracy = 100 * correct / total

        train_losses.append(avg_loss)
        train_accuracies.append(accuracy)

        print(f"Epoch [{epoch+1}/{num_epochs}] - Loss: {avg_loss:.4f}, Accuracy: {accuracy:.2f}%")

        # Save best model
        if accuracy > best_accuracy:
            best_accuracy = accuracy
            torch.save(model.state_dict(), MODEL_PATH)
            print(f"✓ Best model saved! (Accuracy: {accuracy:.2f}%)")

        scheduler.step()

    print("\n✓ Training completed!")

    # Save final model
    torch.save(model.state_dict(), '/content/drive/MyDrive/final_cnn_model.pth')
    print("✓ Final model saved!")
    # Plot training history
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    ax1.plot(train_losses, color='#FF6B6B', linewidth=2, marker='o', markersize=4)
    ax1.set_xlabel('Epoch', fontsize=12)
    ax1.set_ylabel('Loss', fontsize=12)
    ax1.set_title('Training Loss Over Time', fontsize=14, fontweight='bold')
    ax1.grid(True, alpha=0.3)

    ax2.plot(train_accuracies, color='#4ECDC4', linewidth=2, marker='o', markersize=4)
    ax2.set_xlabel('Epoch', fontsize=12)
    ax2.set_ylabel('Accuracy (%)', fontsize=12)
    ax2.set_title('Training Accuracy Over Time', fontsize=14, fontweight='bold')
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('/content/training_history.png', dpi=100, bbox_inches='tight')
    plt.show()
    print("✓ Training history saved!")
else:
    print("\n✓ Skipping training - using pre-trained model")

# ============================================================================
# CELL 9: EVALUATE MODEL
# ============================================================================

print("\n" + "="*60)
print("EVALUATING MODEL")
print("="*60 + "\n")

model.eval()

all_predictions = []
all_labels = []
all_confidences = []

with torch.no_grad():
    for images, labels in tqdm(test_loader, desc="Evaluating"):
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        probabilities = torch.softmax(outputs, dim=1)
        _, predictions = torch.max(outputs, 1)

        all_predictions.extend(predictions.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        all_confidences.extend(probabilities.max(dim=1)[0].cpu().numpy())

all_predictions = np.array(all_predictions)
all_labels = np.array(all_labels)
all_confidences = np.array(all_confidences)

print("✓ Evaluation complete!")

# ============================================================================
# CELL 8B: PLOT TRAINING HISTORY (Only if training happened)
# ============================================================================

if RETRAIN and train_losses:  # Only plot if training was done
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    # Loss
    ax1.plot(train_losses, color='#FF6B6B', linewidth=2, marker='o', markersize=4)
    ax1.set_xlabel('Epoch', fontsize=12)
    ax1.set_ylabel('Loss', fontsize=12)
    ax1.set_title('Training Loss Over Time', fontsize=14, fontweight='bold')
    ax1.grid(True, alpha=0.3)

    # Accuracy
    ax2.plot(train_accuracies, color='#4ECDC4', linewidth=2, marker='o', markersize=4)
    ax2.set_xlabel('Epoch', fontsize=12)
    ax2.set_ylabel('Accuracy (%)', fontsize=12)
    ax2.set_title('Training Accuracy Over Time', fontsize=14, fontweight='bold')
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('/content/training_history.png', dpi=100, bbox_inches='tight')
    plt.show()
    print("✓ Training history saved!")
else:
    print("✓ Skipping training history plot (using pre-trained model)")

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

"""Metrices  Calculation"""

accuracy = accuracy_score(all_labels, all_predictions)
print(f"\n{'='*50}")
print(f"OVERALL ACCURACY: {accuracy*100:.2f}%")
print(f"{'='*50}\n")

# Classification Report
class_names = full_dataset.classes
print("CLASSIFICATION REPORT:")
print(classification_report(all_labels, all_predictions, target_names=class_names))

# Confusion Matrix
cm = confusion_matrix(all_labels, all_predictions)

"""Confusion Matrix"""

plt.figure(figsize=(6, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix', fontsize=12, fontweight='bold')
plt.ylabel('True Label', fontsize=10)
plt.xlabel('Predicted Label', fontsize=10)
plt.tight_layout()
plt.savefig('/content/confusion_matrix.png', dpi=100, bbox_inches='tight')
plt.show()

# ==================== Plot 2: Per-Class Accuracy ====================

per_class_accuracy = cm.diagonal() / cm.sum(axis=1)

plt.figure(figsize=(10, 4))
colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#FFA07A']
bars = plt.bar(class_names, per_class_accuracy * 100, color=colors, alpha=0.8, edgecolor='black', linewidth=1.5)
plt.ylabel('Accuracy (%)', fontsize=12, fontweight='bold')
plt.title('Per-Class Test Accuracy', fontsize=16, fontweight='bold')
plt.ylim([0, 105])
plt.grid(axis='y', alpha=0.3)

for i, (bar, acc) in enumerate(zip(bars, per_class_accuracy)):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 2,
             f'{acc*100:.1f}%', ha='center', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.savefig('/content/per_class_accuracy.png', dpi=100, bbox_inches='tight')
plt.show()
print("✓ Per-class accuracy saved!")

# ==================== Plot 3: Confidence Distribution ====================
plt.figure(figsize=(10, 4))
plt.hist(all_confidences, bins=30, color='skyblue', edgecolor='black', alpha=0.7)
plt.axvline(all_confidences.mean(), color='red', linestyle='--', linewidth=2,
            label=f'Mean: {all_confidences.mean():.3f}')
plt.xlabel('Confidence Score', fontsize=12, fontweight='bold')
plt.ylabel('Frequency', fontsize=12, fontweight='bold')
plt.title('Model Confidence Distribution on Test Set', fontsize=16, fontweight='bold')
plt.legend(fontsize=11)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('/content/confidence_distribution.png', dpi=100, bbox_inches='tight')
plt.show()
print("✓ Confidence distribution saved!")

# ==================== PLOT 4: CORRECT VS INCORRECT BY CONFIDENCE ====================
correct = (all_predictions == all_labels)

plt.figure(figsize=(10, 6))
plt.scatter(all_confidences[correct], np.ones_like(all_confidences[correct]),
           alpha=0.5, s=40, label=f'Correct ({correct.sum()})', color='green')
plt.scatter(all_confidences[~correct], np.zeros_like(all_confidences[~correct]),
           alpha=0.5, s=40, label=f'Incorrect ({(~correct).sum()})', color='red')
plt.xlabel('Confidence Score', fontsize=12, fontweight='bold')
plt.ylabel('Prediction Correctness', fontsize=12, fontweight='bold')
plt.title('Confidence vs Prediction Accuracy', fontsize=16, fontweight='bold')
plt.yticks([0, 1], ['Incorrect', 'Correct'])
plt.legend(fontsize=11)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('/content/confidence_vs_accuracy.png', dpi=100, bbox_inches='tight')
plt.show()
print("✓ Confidence vs accuracy plot saved!")

# ==================== Detailed Analysis ====================
print(f"\n{'='*60}")
print("DETAILED TEST SET ANALYSIS:")
print(f"{'='*60}")
print(f"Total Test Samples: {len(all_labels)}")
print(f"Correct Predictions: {correct.sum()}")
print(f"Incorrect Predictions: {(~correct).sum()}")
print(f"Average Confidence: {all_confidences.mean():.4f}")
print(f"Min Confidence: {all_confidences.min():.4f}")
print(f"Max Confidence: {all_confidences.max():.4f}")
print(f"Std Dev Confidence: {all_confidences.std():.4f}")

print(f"\n{'='*60}")
print("PER-CLASS BREAKDOWN:")
print(f"{'='*60}")
for i, class_name in enumerate(class_names):
    class_total = (all_labels == i).sum()
    class_correct = ((all_labels == i) & (all_predictions == i)).sum()
    class_accuracy = class_correct / class_total * 100 if class_total > 0 else 0
    print(f"{class_name:20s} - Accuracy: {class_accuracy:6.2f}% ({class_correct}/{class_total})")

"""Resnet Model"""

print("\n" + "="*70)
print("RESNET MODEL - TRANSFER LEARNING")
print("="*70)

# ResNet paths
RESNET_MODEL_PATH = '/content/drive/MyDrive/best_resnet_model.pth'


# ============================================================================
# NEW CELL: RESNET - TRANSFORMS (ImageNet normalization)
# ============================================================================

resnet_train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomRotation(10),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))
])

resnet_test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))
])

print("✓ ResNet transforms defined")

# ============================================================================
# NEW CELL: RESNET - LOAD DATASET WITH NEW TRANSFORMS
# ============================================================================

print("Loading dataset for ResNet...")
resnet_full_dataset = datasets.ImageFolder(f'{DATASET_PATH}/cotton', transform=resnet_train_transform)

resnet_train_size = int(0.8 * len(resnet_full_dataset))
resnet_test_size = len(resnet_full_dataset) - resnet_train_size

resnet_train_dataset, resnet_test_dataset = random_split(resnet_full_dataset, [resnet_train_size, resnet_test_size])
resnet_test_dataset.dataset.transform = resnet_test_transform

resnet_train_loader = DataLoader(resnet_train_dataset, batch_size=32, shuffle=True, num_workers=2)
resnet_test_loader = DataLoader(resnet_test_dataset, batch_size=32, shuffle=False, num_workers=2)

print(f"✓ ResNet dataset loaded: {len(resnet_full_dataset)} total samples")

import torchvision.models as models

# ============================================================================
# NEW CELL: RESNET - DEFINE MODEL CLASS
# ============================================================================

class ResNetModel(nn.Module):
    def __init__(self, num_classes):
        super(ResNetModel, self).__init__()

        # Load pre-trained ResNet50
        self.resnet = models.resnet50(pretrained=True)

        # Freeze early layers (keeps ImageNet features)
        for param in list(self.resnet.parameters())[:-20]:
            param.requires_grad = False

        # Replace final layer for 4 classes
        num_features = self.resnet.fc.in_features
        self.resnet.fc = nn.Sequential(
            nn.Linear(num_features, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(0.5),
            nn.Linear(512, 256),
            nn.ReLU(inplace=True),
            nn.Dropout(0.5),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        return self.resnet(x)

print("✓ ResNet50 model class defined")

# ============================================================================
# NEW CELL: RESNET - INITIALIZE MODEL
# ============================================================================

resnet_model = ResNetModel(num_classes=4).to(device)
resnet_criterion = nn.CrossEntropyLoss()
resnet_optimizer = optim.Adam(resnet_model.parameters(), lr=0.0001)
resnet_scheduler = optim.lr_scheduler.StepLR(resnet_optimizer, step_size=5, gamma=0.1)

print("✓ ResNet model initialized")
print(f"  - Total parameters: {sum(p.numel() for p in resnet_model.parameters()):,}")
print(f"  - Trainable parameters: {sum(p.numel() for p in resnet_model.parameters() if p.requires_grad):,}")

# ============================================================================
# NEW CELL: RESNET - LOAD OR TRAIN
# ============================================================================

if os.path.exists(RESNET_MODEL_PATH):
    print("\nLoading pre-trained ResNet model from Google Drive...")
    resnet_model.load_state_dict(torch.load(RESNET_MODEL_PATH))
    resnet_model.eval()
    print("✓ ResNet model loaded successfully!")
    RESNET_RETRAIN = False
else:
    print("\nNo pre-trained ResNet model found. Training now...")
    RESNET_RETRAIN = True

# ============================================================================
# NEW CELL: RESNET - TRAIN MODEL
# ============================================================================

if RESNET_RETRAIN:
    print("\n" + "="*70)
    print("TRAINING RESNET MODEL")
    print("="*70 + "\n")

    resnet_num_epochs = 15
    resnet_best_accuracy = 0.0
    resnet_train_losses = []
    resnet_train_accuracies = []

    for epoch in range(resnet_num_epochs):
        resnet_model.train()
        resnet_total_loss = 0
        resnet_correct = 0
        resnet_total = 0

        resnet_pbar = tqdm(resnet_train_loader, desc=f"ResNet Epoch [{epoch+1}/{resnet_num_epochs}]")

        for images, labels in resnet_pbar:
            images, labels = images.to(device), labels.to(device)

            outputs = resnet_model(images)
            loss = resnet_criterion(outputs, labels)

            resnet_optimizer.zero_grad()
            loss.backward()
            resnet_optimizer.step()

            resnet_total_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            resnet_total += labels.size(0)
            resnet_correct += (predicted == labels).sum().item()

            resnet_pbar.set_postfix({
                'Loss': f'{resnet_total_loss / (resnet_total / 32):.4f}',
                'Acc': f'{100 * resnet_correct / resnet_total:.2f}%'
            })

        resnet_avg_loss = resnet_total_loss / len(resnet_train_loader)
        resnet_accuracy = 100 * resnet_correct / resnet_total

        resnet_train_losses.append(resnet_avg_loss)
        resnet_train_accuracies.append(resnet_accuracy)

        print(f"Epoch [{epoch+1}/{resnet_num_epochs}] - Loss: {resnet_avg_loss:.4f}, Accuracy: {resnet_accuracy:.2f}%")

        if resnet_accuracy > resnet_best_accuracy:
            resnet_best_accuracy = resnet_accuracy
            torch.save(resnet_model.state_dict(), RESNET_MODEL_PATH)
            print(f"✓ Best ResNet model saved! (Accuracy: {resnet_accuracy:.2f}%)")

        resnet_scheduler.step()

    print("\n✓ ResNet training completed!")

    # Save history
    resnet_history = {
        'train_losses': resnet_train_losses,
        'train_accuracies': resnet_train_accuracies
    }
    with open('/content/drive/MyDrive/resnet_training_history.json', 'w') as f:
        json.dump(resnet_history, f)

      # Plot
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    ax1.plot(resnet_train_losses, color='#FF6B6B', linewidth=2, marker='o', markersize=4)
    ax1.set_xlabel('Epoch', fontsize=12)
    ax1.set_ylabel('Loss', fontsize=12)
    ax1.set_title('ResNet Training Loss', fontsize=14, fontweight='bold')
    ax1.grid(True, alpha=0.3)

    ax2.plot(resnet_train_accuracies, color='#4ECDC4', linewidth=2, marker='o', markersize=4)
    ax2.set_xlabel('Epoch', fontsize=12)
    ax2.set_ylabel('Accuracy (%)', fontsize=12)
    ax2.set_title('ResNet Training Accuracy', fontsize=14, fontweight='bold')
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('/content/resnet_training_history.png', dpi=100, bbox_inches='tight')
    plt.show()
    print("✓ ResNet training history saved!")
else:
    print("\n✓ Skipping ResNet training - using pre-trained model")

# ============================================================================
# NEW CELL: RESNET - EVALUATE
# ============================================================================

print("\n" + "="*70)
print("EVALUATING RESNET MODEL")
print("="*70 + "\n")

resnet_model.eval()

resnet_all_predictions = []
resnet_all_labels = []
resnet_all_confidences = []

with torch.no_grad():
    for images, labels in tqdm(resnet_test_loader, desc="Evaluating ResNet"):
        images, labels = images.to(device), labels.to(device)

        outputs = resnet_model(images)
        probabilities = torch.softmax(outputs, dim=1)
        _, predictions = torch.max(outputs, 1)

        resnet_all_predictions.extend(predictions.cpu().numpy())
        resnet_all_labels.extend(labels.cpu().numpy())
        resnet_all_confidences.extend(probabilities.max(dim=1)[0].cpu().numpy())

resnet_all_predictions = np.array(resnet_all_predictions)
resnet_all_labels = np.array(resnet_all_labels)
resnet_all_confidences = np.array(resnet_all_confidences)

print("✓ ResNet evaluation complete!")

# ============================================================================
# NEW CELL: RESNET - RESULTS
# ============================================================================

print("\n" + "="*70)
print("RESNET - DETAILED TEST SET ANALYSIS")
print("="*70)

resnet_total_samples = len(resnet_all_labels)
resnet_correct_predictions = np.sum(resnet_all_predictions == resnet_all_labels)
resnet_incorrect_predictions = resnet_total_samples - resnet_correct_predictions
resnet_accuracy_percent = (resnet_correct_predictions / resnet_total_samples) * 100

print(f"\nTotal Test Samples: {resnet_total_samples}")
print(f"Correct Predictions: {resnet_correct_predictions}")
print(f"Incorrect Predictions: {resnet_incorrect_predictions}")
print(f"\n✓ Accuracy: {resnet_accuracy_percent:.2f}%")
print(f"\nAverage Confidence: {resnet_all_confidences.mean():.4f}")
print(f"Min Confidence: {resnet_all_confidences.min():.4f}")
print(f"Max Confidence: {resnet_all_confidences.max():.4f}")
print(f"Std Dev Confidence: {resnet_all_confidences.std():.4f}")

print("\n" + "="*70)

# ============================================================================
# NEW CELL: RESNET - CONFUSION MATRIX
# ============================================================================

resnet_class_names = resnet_full_dataset.classes
resnet_cm = confusion_matrix(resnet_all_labels, resnet_all_predictions)

plt.figure(figsize=(10, 8))
sns.heatmap(resnet_cm, annot=True, fmt='d', cmap='Blues', xticklabels=resnet_class_names, yticklabels=resnet_class_names)
plt.title('ResNet Confusion Matrix', fontsize=14, fontweight='bold')
plt.ylabel('True Label', fontsize=12)
plt.xlabel('Predicted Label', fontsize=12)
plt.tight_layout()
plt.savefig('/content/resnet_confusion_matrix.png', dpi=100, bbox_inches='tight')
plt.show()

print("✓ ResNet confusion matrix saved!")

# NEW CELL: RESNET - DETAILED VISUALIZATIONS
# ============================================================================

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Confidence Distribution
axes[0, 0].hist(resnet_all_confidences, bins=30, color='#4ECDC4', edgecolor='black', alpha=0.7)
axes[0, 0].axvline(resnet_all_confidences.mean(), color='red', linestyle='--', linewidth=2, label=f'Mean: {resnet_all_confidences.mean():.4f}')
axes[0, 0].set_xlabel('Confidence', fontsize=11)
axes[0, 0].set_ylabel('Frequency', fontsize=11)
axes[0, 0].set_title('ResNet Confidence Distribution', fontsize=12, fontweight='bold')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

# Accuracy vs Confidence
axes[0, 1].scatter(resnet_all_confidences, (resnet_all_predictions == resnet_all_labels).astype(int), alpha=0.5, color='#FF6B6B')
axes[0, 1].set_xlabel('Confidence', fontsize=11)
axes[0, 1].set_ylabel('Correct (1) / Incorrect (0)', fontsize=11)
axes[0, 1].set_title('ResNet Accuracy vs Confidence', fontsize=12, fontweight='bold')
axes[0, 1].grid(True, alpha=0.3)

# Per-class Accuracy
resnet_class_accuracies = []
for idx in range(len(resnet_class_names)):
    class_mask = resnet_all_labels == idx
    class_correct = np.sum((resnet_all_predictions == resnet_all_labels) & class_mask)
    class_total = np.sum(class_mask)
    class_acc = (class_correct / class_total) * 100 if class_total > 0 else 0
    resnet_class_accuracies.append(class_acc)

axes[1, 0].bar(resnet_class_names, resnet_class_accuracies, color='#4ECDC4', edgecolor='black', alpha=0.7)
axes[1, 0].set_ylabel('Accuracy (%)', fontsize=11)
axes[1, 0].set_title('ResNet Per-Class Accuracy', fontsize=12, fontweight='bold')
axes[1, 0].set_ylim([0, 105])
for i, v in enumerate(resnet_class_accuracies):
    axes[1, 0].text(i, v + 1, f'{v:.1f}%', ha='center', fontsize=10)
axes[1, 0].grid(True, alpha=0.3, axis='y')

# Per-class Confidence
resnet_class_confidences = []
for idx in range(len(resnet_class_names)):
    class_mask = resnet_all_labels == idx
    class_conf = resnet_all_confidences[class_mask].mean() if np.sum(class_mask) > 0 else 0
    resnet_class_confidences.append(class_conf)

axes[1, 1].bar(resnet_class_names, resnet_class_confidences, color='#FFD93D', edgecolor='black', alpha=0.7)
axes[1, 1].set_ylabel('Average Confidence', fontsize=11)
axes[1, 1].set_title('ResNet Per-Class Average Confidence', fontsize=12, fontweight='bold')
axes[1, 1].set_ylim([0, 1.05])
for i, v in enumerate(resnet_class_confidences):
    axes[1, 1].text(i, v + 0.02, f'{v:.4f}', ha='center', fontsize=9)
axes[1, 1].grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig('/content/resnet_detailed_analysis.png', dpi=100, bbox_inches='tight')
plt.show()

print("\n✓ ResNet detailed analysis visualization saved!")
print("\n" + "="*70)
print("RESNET EVALUATION COMPLETE!")
print("="*70)

# NEW CELL: CNN vs RESNET COMPARISON
# ============================================================================

print("\n" + "="*70)
print("CNN vs RESNET COMPARISON")
print("="*70)

correct = (all_predictions == all_labels).sum()
total = len(all_labels)

cnn_accuracy = (correct / total) * 100
resnet_accuracy = resnet_accuracy_percent

print(f"\nCNN Accuracy:    {cnn_accuracy:.2f}%")
print(f"ResNet Accuracy: {resnet_accuracy:.2f}%")
print(f"Difference:      {abs(resnet_accuracy - cnn_accuracy):+.2f}%")

# Comparison plot
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

models_list = ['CNN', 'ResNet']
accuracies = [cnn_accuracy, resnet_accuracy]
colors = ['#FF6B6B', '#4ECDC4']

ax1.bar(models_list, accuracies, color=colors, edgecolor='black', alpha=0.7, width=0.5)
ax1.set_ylabel('Accuracy (%)', fontsize=12)
ax1.set_title('Model Accuracy Comparison', fontsize=14, fontweight='bold')
ax1.set_ylim([95, 101])
for i, v in enumerate(accuracies):
    ax1.text(i, v + 0.2, f'{v:.2f}%', ha='center', fontsize=12, fontweight='bold')
ax1.grid(True, alpha=0.3, axis='y')

# Confidence comparison
ax2.bar(models_list, [all_confidences.mean(), resnet_all_confidences.mean()], color=colors, edgecolor='black', alpha=0.7, width=0.5)
ax2.set_ylabel('Average Confidence', fontsize=12)
ax2.set_title('Model Confidence Comparison', fontsize=14, fontweight='bold')
ax2.set_ylim([0.98, 1.0])
for i, (v1, v2) in enumerate([(all_confidences.mean(), resnet_all_confidences.mean())]):
    ax2.text(0, v1 + 0.002, f'{v1:.4f}', ha='center', fontsize=11, fontweight='bold')
    ax2.text(1, v2 + 0.002, f'{v2:.4f}', ha='center', fontsize=11, fontweight='bold')
ax2.grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig('/content/cnn_vs_resnet_comparison.png', dpi=100, bbox_inches='tight')
plt.show()

print("\n✓ Comparison visualization saved!")

"""## **GRAD CAM IMPLEMENTATION**"""

import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image
from torchvision import transforms
from google.colab import files, drive
import os
from tqdm import tqdm

"""# ==================== GRAD-CAM CLASS ===================="""

class GradCAM:
    """
    Gradient-weighted Class Activation Mapping
    Shows which parts of image model uses for prediction
    """

    def __init__(self, model, target_layer):
        """
        Args:
            model: Your trained model (CNN or ResNet)
            target_layer: Last conv layer to visualize
        """
        self.model = model
        self.target_layer = target_layer
        self.gradients = None
        self.activations = None

        # Register hooks to capture gradients and activations
        self.target_layer.register_forward_hook(self.save_activation)
        self.target_layer.register_backward_hook(self.save_gradient)

    def save_activation(self, module, input, output):
        """Save activation maps during forward pass"""
        self.activations = output.detach()

    def save_gradient(self, module, grad_input, grad_output):
        """Save gradients during backward pass"""
        self.gradients = grad_output[0].detach()

    def generate_cam(self, input_tensor, target_class=None):
        """
        Generate Class Activation Map

        Args:
            input_tensor: Input image (1, 3, 224, 224)
            target_class: Class to visualize (None = predicted class)

        Returns:
            cam: Heatmap (224, 224)
            target_class: Predicted or target class
        """
        self.model.eval()

        # Forward pass
        output = self.model(input_tensor)

        # Get target class
        if target_class is None:
            target_class = output.argmax(dim=1).item()

        # Backward pass
        self.model.zero_grad()
        target_score = output[0, target_class]
        target_score.backward()

        # Calculate Grad-CAM
        pooled_gradients = torch.mean(self.gradients, dim=[0, 2, 3])

        for i in range(self.activations.shape[1]):
            self.activations[:, i, :, :] *= pooled_gradients[i]

        cam = torch.mean(self.activations, dim=1).squeeze().cpu().numpy()

        # Normalize to 0-1
        cam = np.maximum(cam, 0)
        cam = cam / (cam.max() + 1e-8)

        # Resize to 224x224
        cam = cv2.resize(cam, (224, 224))

        return cam, target_class

    def visualize_cam(self, image_tensor, original_image, class_names, target_class=None, confidence=None):
        """
        Visualize CAM on image

        Args:
            image_tensor: Tensor (1, 3, 224, 224)
            original_image: PIL Image or numpy array
            class_names: List of class names
            target_class: Target class (optional)
            confidence: Confidence score (optional)

        Returns:
            fig: Matplotlib figure
            cam: Heatmap
            predicted_class: Predicted class
        """
        # Generate CAM
        cam, predicted_class = self.generate_cam(image_tensor, target_class)

        # Convert to numpy
        if not isinstance(original_image, np.ndarray):
            original_image = np.array(original_image)

        # Resize if needed
        if original_image.shape[:2] != (224, 224):
            original_image = cv2.resize(original_image, (224, 224))

        # Create heatmap
        heatmap = cv2.applyColorMap(np.uint8(255 * cam), cv2.COLORMAP_JET)
        heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)

        # Blend
        blended = cv2.addWeighted(original_image, 0.6, heatmap, 0.4, 0)

        # Plot
        fig, axes = plt.subplots(1, 3, figsize=(16, 5))

        # Original
        axes[0].imshow(original_image)
        axes[0].set_title('Original Image', fontsize=13, fontweight='bold')
        axes[0].axis('off')

        # Heatmap
        axes[1].imshow(cam, cmap='jet')
        axes[1].set_title('Grad-CAM Heatmap', fontsize=13, fontweight='bold')
        axes[1].axis('off')

        # Blended
        title = f'Prediction: {class_names[predicted_class]}'
        if confidence:
            title += f' ({confidence:.2f}%)'
        axes[2].imshow(blended)
        axes[2].set_title(title, fontsize=13, fontweight='bold', color='green')
        axes[2].axis('off')

        plt.tight_layout()
        return fig, cam, predicted_class

# ==================== INPUT FUNCTIONS ====================

def upload_and_visualize_gradcam(model, gradcam, class_names, transform, device):
    """
    Upload image from computer and visualize Grad-CAM

    Usage:
        upload_and_visualize_gradcam(model, gradcam, class_names, transform, device)
    """
    print("\n" + "="*60)
    print("UPLOAD IMAGE FROM YOUR COMPUTER")
    print("="*60)

    uploaded = files.upload()

    for filename in uploaded.keys():
        print(f"\n✓ Uploaded: {filename}")

        # Load image
        image = Image.open(filename).convert('RGB')
        image_for_display = image.copy()

        # Transform
        image_tensor = transform(image).unsqueeze(0).to(device)

        # Predict
        with torch.no_grad():
            output = model(image_tensor)
            probabilities = torch.softmax(output, dim=1)[0]
            predicted_class = output.argmax(dim=1).item()
            confidence = probabilities[predicted_class].item() * 100

        print(f"\nPrediction: {class_names[predicted_class]}")
        print(f"Confidence: {confidence:.2f}%")
        print("\nAll Class Probabilities:")
        for i, class_name in enumerate(class_names):
            print(f"  {class_name:20s}: {probabilities[i]*100:.2f}%")

        # Grad-CAM visualization
        fig, cam, _ = gradcam.visualize_cam(
            image_tensor,
            image_for_display,
            class_names,
            confidence=confidence
        )
        plt.show()

        # Save to Drive
        save_path = f'/content/drive/MyDrive/gradcam_{filename}'
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"✓ Saved to Google Drive: {save_path}")

def gradcam_single_image(image_path, model, gradcam, class_names, transform, device):
    """
    Apply Grad-CAM to single image from dataset

    Usage:
        gradcam_single_image('/content/dataset/cotton/healthy/image.jpg', model, gradcam, class_names, transform, device)
    """
    print("\n" + "="*60)
    print("GRAD-CAM FOR SINGLE IMAGE")
    print("="*60)

    if not os.path.exists(image_path):
        print(f"✗ Image not found: {image_path}")
        return

    print(f"✓ Loading: {image_path}")

    image = Image.open(image_path).convert('RGB')
    image_for_display = image.copy()

    image_tensor = transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        output = model(image_tensor)
        probabilities = torch.softmax(output, dim=1)[0]
        predicted_class = output.argmax(dim=1).item()
        confidence = probabilities[predicted_class].item() * 100

    print(f"\nPrediction: {class_names[predicted_class]}")
    print(f"Confidence: {confidence:.2f}%")
    print("\nAll Class Probabilities:")
    for i, class_name in enumerate(class_names):
        print(f"  {class_name:20s}: {probabilities[i]*100:.2f}%")

    fig, cam, _ = gradcam.visualize_cam(
        image_tensor,
        image_for_display,
        class_names,
        confidence=confidence
    )
    plt.show()

def gradcam_batch_images(folder_path, model, gradcam, class_names, transform, device, num_images=5):
    """
    Apply Grad-CAM to multiple images from folder

    Usage:
        gradcam_batch_images('/content/dataset/cotton/healthy', model, gradcam, class_names, transform, device, num_images=5)
    """
    print("\n" + "="*60)
    print(f"GRAD-CAM FOR {num_images} IMAGES")
    print("="*60)

    if not os.path.exists(folder_path):
        print(f"✗ Folder not found: {folder_path}")
        return

    image_files = [f for f in os.listdir(folder_path)
                   if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

    print(f"Found {len(image_files)} images in {folder_path}\n")

    for idx, image_file in enumerate(image_files[:num_images]):
        image_path = os.path.join(folder_path, image_file)

        print(f"[{idx+1}/{min(num_images, len(image_files))}] Processing: {image_file}")

        try:
            image = Image.open(image_path).convert('RGB')
            image_for_display = image.copy()

            image_tensor = transform(image).unsqueeze(0).to(device)

            with torch.no_grad():
                output = model(image_tensor)
                probabilities = torch.softmax(output, dim=1)[0]
                predicted_class = output.argmax(dim=1).item()
                confidence = probabilities[predicted_class].item() * 100

            print(f"  → Prediction: {class_names[predicted_class]} ({confidence:.2f}%)")

            fig, cam, _ = gradcam.visualize_cam(
                image_tensor,
                image_for_display,
                class_names,
                confidence=confidence
            )
            plt.show()

        except Exception as e:
            print(f"  ✗ Error: {e}")

from torchvision import transforms

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

print("✓ Transforms defined!")

# Get the last convolutional layer
target_layer = model.features[-1]

# Initialize Grad-CAM
gradcam = GradCAM(model, target_layer)

print("✓ Grad-CAM initialized!")

# ==================== UPLOAD IMAGE FROM COMPUTER ====================
print("\n" + "="*60)
print("UPLOAD IMAGE FROM YOUR COMPUTER")
print("="*60)
print("\n⬇️ Click 'Choose Files' button below to select an image\n")

uploaded = files.upload()

for filename in uploaded.keys():
    print(f"\n✓ File uploaded: {filename}")

    # Load image
    image = Image.open(filename).convert('RGB')
    image_for_display = image.copy()

    # Transform for model
    image_tensor = transform(image).unsqueeze(0).to(device)

    print("\n🔍 Making prediction...")

    # Get prediction
    with torch.no_grad():
        output = model(image_tensor)
        probabilities = torch.softmax(output, dim=1)[0]
        predicted_class = output.argmax(dim=1).item()
        confidence = probabilities[predicted_class].item() * 100

    # Display results
    print(f"\n{'='*60}")
    print("PREDICTION RESULTS")
    print(f"{'='*60}")
    print(f"\n🎯 Main Prediction: {class_names[predicted_class]}")
    print(f"📊 Confidence: {confidence:.2f}%")

    print("\n📈 All Class Probabilities:")
    for i, class_name in enumerate(class_names):
        prob = probabilities[i].item() * 100
        print(f"   {class_name:20s}: {prob:6.2f}%")

    print(f"\n{'='*60}")
    print("GENERATING GRAD-CAM...")
    print(f"{'='*60}\n")

    # Generate and display Grad-CAM
    fig, cam, _ = gradcam.visualize_cam(
        image_tensor,
        image_for_display,
        class_names,
        confidence=confidence
    )
    plt.show()

    # Save to Google Drive
    save_path = f'/content/drive/MyDrive/gradcam_{filename}'
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"\n✓ Visualization saved to Google Drive: {save_path}")